/** Builds a valid POST /organisations body. Slug is generated by the API. */
export function buildOrgPayload(name: string, ukprn?: string) {
  const resolvedUkprn =
    ukprn ?? String(Date.now() % 100_000_000).padStart(8, '0');

  return {
    name,
    ukprn: resolvedUkprn,
    address: '1 Test Lane',
    city: 'London',
    postcode: 'SW1A 1AA',
    country: 'United Kingdom',
    orgEmail: `info@${resolvedUkprn}.co.uk`,
  };
}
